config/routes.rb
Rails.application.routes.draw do
	resources :posts, only:[:new, :create, :index]

	resources :users, except: [:new, :create]

	root "static_pages#home"

	get '/signup', to: "users#new"

	post '/signup', to: 'users#create'

	get '/login', to: "sessions#new"

	post '/login', to: 'sessions#create'

	delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, presence: true, length: {maximum: 255}
	validates :user_id, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save :downcase_email
	validates :password, presence: true, length: {minimum: 8}, allow_nil: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
					  format: { with: VALID_EMAIL_REGEX},
					  uniqueness: {case_sensitive: false}
	validates :name, presence: true, length: {maximum: 60}, uniqueness: true
	has_secure_password
	has_many :posts

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		self.remember_token = nil
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)													  
	end

	private

	def downcase_email
		email.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only:[:new, :create]

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		flash[:success] = "Post added!"
  		redirect_to posts_path
  	else
  		render 'new'
  	end
  end

  def index
  	@posts = Post.all.order('posts.created_at DESC')
  end
end

private 

	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = "Please log in"
			redirect_to login_url
		end
	end

	def post_params
		params.require(:post).permit(:body, :user_id)
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in(user)
			remember(user)
			redirect_user_or(user)
		else
			flash.now[:danger] = "Invlaid email/password combination"
			render 'new'
		end
	end

	def destroy
		user = User.find_by(id: session[:user_id])
		log_out(user)
		redirect_to login_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:show, :index, :edit, :destroy]
	before_action :correct_user, only:[:edit]
	before_action :is_admin?, only: [:destroy]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in(@user)
			flash[:success] = "Welcome to Members Only!"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated!"
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end

	def index
		@users = User.all.paginate(page: params[:page])
	end

	def destroy
		@user = User.find(params[:id])
		@user.delete
		redirect_to users_path
	end

	private

	def logged_in_user
		unless logged_in?
			store_location
			flash[:danger] = "Please log in"
			redirect_to login_url
		end
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to current_user unless current_user?(@user)
	end

	def is_admin?
		@user = current_user
		redirect_to root_url unless @user.admin?
	end

	def user_params
		params.require(:user).permit(:email, :name, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = "")
		base_title = "Members Only"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def current_user?(user)
		user == current_user
	end

	def logged_in?
		!current_user.nil?
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end

	def redirect_user_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <% if logged_in? %>
      	<li><%= link_to "Profile", current_user %></li>
      <% else %>
      	<li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
    <%= link_to "Members Only", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Posts", posts_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render 'layouts/header' %>
  	 <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>All posts</h2>
		<% @posts.each do |post| %>
			<div class="user_post">
				<p>
					<%= post.body %>
				</p>
				<% if current_user %>
				<h3>
					<%= link_to post.user.name, post.user %>
				</h3>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Create a Post</h2>
		<%= form_for(@post) do |f| %>
			<%= render 'shared/post_error_messages', object: @post %>

			<%= f.label :body, 'Post' %>
			<%= f.text_area :body, class: 'form-control' %>

			<%= f.hidden_field :user_id, :value => session[:user_id] %>

			<%= f.submit "Create post", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_post_error_messages.html.erb
<% if @post.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger">
		The form contains <%= pluralize(@post.errors.count, "error") %>
	</div>
	<ul>
		<% @post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Welcome to Members Only</h1>
<h2>
  The App where you can post anonomously!
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit "+@user.name) %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Edit <%= @user.name %></h1>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Update", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Users</h1>
		<%= will_paginate %>
		<% @users.each do |user| %>
			<%= link_to user.name, user %>
			<% if current_user.admin? && !current_user?(user) %>
				| <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"} %>
			<% end %>
			<hr>
		<% end %>
		<%= will_paginate %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Sign up</h1>
		<%= form_for(@user, url: '/signup') do |f| %>
			<%= render 'shared/error_messages', object: @user %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Sign up", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name.capitalize) %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1><%= @user.name %></h1>
		<% @posts.each do |post| %>
			<div class="user_post">
				<p>
					<%= post.body %>
				</p>
			</div>
		<% end %>
	</div>
</div>